# Generated by Django 5.1.3 on 2024-12-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
