# Generated by Django 5.0.2 on 2024-02-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0002_student_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
