# Generated by Django 5.1.3 on 2024-12-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0003_remove_student_phone_number_student_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
