# Generated by Django 5.0.2 on 2024-02-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0006_coordinatofeedbacks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoordinatoFeedbacks',
            new_name='CoordinatorFeedbacks',
        ),
    ]
