# Generated by Django 5.0.2 on 2024-03-04 22:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0008_coordinatorannouncements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('order', models.IntegerField(unique=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('current_phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='projectsApp.phases')),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='projectsApp.lecturer')),
                ('project', models.ForeignKey(limit_choices_to={'status': 'approved'}, on_delete=django.db.models.deletion.CASCADE, to='projectsApp.projects')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revision_requested', 'Revision Required')], default='pending', max_length=50)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsApp.phases')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsApp.proposal')),
            ],
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
    ]
