# Generated by Django 5.0.2 on 2024-03-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0009_phases_proposal_documents_delete_milestone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
