# Generated by Django 5.0.2 on 2024-03-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0011_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
