# Generated by Django 5.0.2 on 2024-03-07 08:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0012_delete_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revision_requested', 'Revision Required')], default='pending', max_length=50)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsApp.phases')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsApp.proposal')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsApp.student')),
            ],
        ),
    ]
