# Generated by Django 5.0.2 on 2024-03-07 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0013_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsApp.projects'),
        ),
    ]
