# Generated by Django 5.0.2 on 2024-03-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0016_alter_documents_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='file_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
