# Generated by Django 5.0.2 on 2024-03-09 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0018_alter_proposal_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projectsApp.phases'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projectsApp.proposal'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projectsApp.student'),
        ),
    ]
