# Generated by Django 5.0.2 on 2024-03-10 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0019_alter_documents_phase_alter_documents_proposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projectsApp.student'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projectsApp.lecturer'),
        ),
    ]
