# Generated by Django 5.0.2 on 2024-03-10 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0020_alter_notifications_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coordinatorfeedbacks',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='projectsApp.lecturer'),
        ),
        migrations.AlterField(
            model_name='coordinatorfeedbacks',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinatorfeedbacks', to='projectsApp.projects'),
        ),
        migrations.AlterField(
            model_name='coordinatorfeedbacks',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinatorfeedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
