# Generated by Django 5.0.2 on 2024-03-10 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0022_resources_coordinatorannouncements_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='file_name',
        ),
    ]
