# Generated by Django 5.0.2 on 2024-03-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0023_remove_resources_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='file_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
