# Generated by Django 5.0.2 on 2024-03-31 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0025_registrationsettings_alter_projects_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationsettings',
            old_name='allowed_intake_year',
            new_name='allowed_year',
        ),
        migrations.RenameField(
            model_name='registrationsettings',
            old_name='registration_open',
            new_name='open',
        ),
    ]
